before_script:
    - apt-get update
    - apt-get install --force-yes -y python lcov
    - apt remove --purge --auto-remove cmake
    - apt install -y software-properties-common lsb-release cmake wget
    - wget https://apt.llvm.org/llvm.sh
    - chmod +x llvm.sh
    - ./llvm.sh 20

build:
    tags:
        - Ubuntu2004-64bit
    script:
        - cmake -DCODE_COVERAGE=ON -DBUILD_TESTS=ON .
        - make
        - ctest --output-on-failure
        - make maxpluslibcoverage
    artifacts:
      expire_in: 14d
      when: always
      paths:
      - ./build/coverage/

format:
    tags:
        - Ubuntu2004-64bit
    script:
        - clang-format-20 --version
        - clang-format-20 --dry-run --Werror `find ./ -type f -name "*.h" -o -name "*.cc" -o -name "*.cpp"`
        
